spring:
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_base
    username: postgres
    password:
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  secure: true
  bucket: user-files